name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: sudo apt-get update && sudo apt-get install -y rsync
      - run: mv dist deploy
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
