name: Format

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: GitHub actions
